/*
 * © OOO "SI IKS LAB", 2022-2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.cxbox.model.core.hbn;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import org.hibernate.annotations.IdGeneratorType;

/**
 * Marks an identifier field as generated by {@link ExtSequenceStyleGenerator}.
 * <p>Analog for {@link jakarta.persistence.GeneratedValue} and {@link org.hibernate.annotations.GenericGenerator)
 * (is deprecated and not work <a href="https://discourse.hibernate.org/t/hibernate-7-sequence-generator-broken/12155/4"> see discourse</a>
 * <p>Example: {@link org.cxbox.model.core.entity.BaseEntity} or {@link org.cxbox.meta.entity.Responsibilities}</p>
 * @see IdGeneratorType
 */
@IdGeneratorType(ExtSequenceStyleGenerator.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD, ElementType.METHOD})
public @interface ExtSequenceId {
}