name: Build project

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches-ignore:
      - 'main'

permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17','21']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: "maven"
      - name: Build with Maven
        run: mvn clean install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Sonar
        if: matrix.java == '21'
        run: >
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594:sonar
          -Dsonar.organization=cx-box
          -Dsonar.projectKey=CX-Box_cxbox-demo
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=$SONAR_TOKEN

  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
          config-file: './.github/dependency-review-config.yml'
          base-ref: ${{ github.event.pull_request.base.sha || 'main' }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}